#!/usr/bin/env node
var SerialApi = require('./lib')
var myrepl = require('repl').start()
const api = SerialApi({
  port: '/dev/ttyACM1'
})
const channel = require('./lib/serialapi/transport/controller-channel').controllerChannel(api)

myrepl.context.SerialApi = SerialApi
myrepl.context.api = api
myrepl.context.channel = channel
