#!/usr/bin/env node
var SerialApi = require('./lib')
var myrepl = require('repl').start()
const api = SerialApi({
  port: '/dev/ttyACM1'
})
const sendData = require('./lib/serialapi/transport/controller-channel')
const sendDataFunc = (command) => sendData(api, command)

myrepl.context.SerialApi = SerialApi
myrepl.context.api = api
myrepl.context.sendData = sendDataFunc
